### PR TITLE
Test CUDA 9.2 build

### PR DESCRIPTION
**Pull request by jchodera**
This PR is testing the CUDA 9.2 build with some other updates to figure out what we will need for an OpenMM 7.3 release.

### CODE REVIEW

**Comment by Lnaden** [comment]
I think you may need to set the proper place to fetch the OpenCL lib from:

https://github.com/omnia-md/conda-dev-recipes/blob/43b548ac80e66cb368bf93ffd90db7dfe3627eb1/openmm/build.sh#L28-L32

I think its just a matter of commenting out the AMD lines and uncommented the Nvidia lines
```
    # AMD APP SDK 3.0 OpenCL
    CMAKE_FLAGS+=" -DOPENCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include/"
    CMAKE_FLAGS+=" -DOPENCL_LIBRARY=/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so"
    # CUDA OpenCL
    #CMAKE_FLAGS+=" -DOPENCL_INCLUDE_DUR=${CUDA_PATH}/include/"
    #CMAKE_FLAGS+=" -DOPENCL_LIBRARY=${CUDA_PATH}/lib64/libOpenCL.so"
```

**Comment by Lnaden** [comment]
Oh! That is a neat new feature in the issue! I did not know GitHub would expand the code from the link!

**Comment by jchodera** [comment]
Thanks! Fixing.

**Comment by jchodera** [comment]
@peastman: I'm testing the build in a docker container locally with `clangdev==6.0.0` and the CUDA 9.2 image, using OpenCL headers from the CUDA toolkit (instead of the AMD APP SDK).

I'm seeing this build error:
```
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /opt/conda/conda-bld/openmm_1529194407685/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/clang
-- Check for working C compiler: /opt/conda/conda-bld/openmm_1529194407685/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/conda/conda-bld/openmm_1529194407685/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/clang++
-- Check for working CXX compiler: /opt/conda/conda-bld/openmm_1529194407685/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:25 (CMAKE_POLICY):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found Doxygen: /opt/conda/conda-bld/openmm_1529194407685/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/doxygen (found version "1.8.10") found components:  doxygen missing components:  dot
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda/ (found version "9.2") 
-- Found OPENCL: /usr/local/cuda/lib64/libOpenCL.so  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "OpenMMCUDA" in directory /opt/conda/conda-bld/openmm_1529194407685/work/platforms/cuda/sharedTarget

-- Configuring incomplete, errors occurred!
See also "/opt/conda/conda-bld/openmm_1529194407685/work/build/CMakeFiles/CMakeOutput.log".
See also "/opt/conda/conda-bld/openmm_1529194407685/work/build/CMakeFiles/CMakeError.log".
```
Any idea what `CUDA_CUDA_LIBRARY` is looking for?

See the modified [`build.sh`](https://github.com/omnia-md/conda-dev-recipes/blob/cuda92/openmm/build.sh)

**Comment by peastman** [comment]
It's looking for libcuda.so.  I think that may come with the driver, so make sure you told it to install that.

**Comment by jchodera** [comment]
D'oh. Our new scheme just installs the toolkits.

What are the requirements regarding which driver must be installed for each CUDA version? Can we install a single recent driver and use that for all CUDA versions?

**Comment by peastman** [comment]
I *think* a newer driver should work with older toolkits.

**Comment by jchodera** [comment]
This appears to be working, so I'll merge in and test in the morning.

**Comment by linusyukwong** [comment]
May I ask how can i compile from source for cuda 9.2?

**Pull request merged**
