### PR TITLE
Update appveyor.yml

### LINKED ISSUE #14: Something wrong with Appveyor
It looks like there is something catastrophically wrong with Appveyor (git not working).

### PR DESCRIPTION
**Pull request by rmcgibbo**
May or may not fix #14

### CODE REVIEW

**Comment by jchodera** [comment]
LOL, looks like AppVeyor is going to be "Queued" forever...

**Comment by rmcgibbo** [comment]
Maybe you can kill the first build that's timing out?

**Comment by jchodera** [comment]
Sorry---I hadn't noticed the earlier build was the culprit.

**Comment by rmcgibbo** [comment]
No, it looks like the cywin stuff didn't help.

**Pull request closed without merging**
