### PR TITLE
openmm clang linux conda builds

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
I've not had much luck finding any instances of people using `clang` for linux builds with anaconda python recipes.

**Comment by jchodera** [comment]
Much of the clang discussion is about `osx`, but some of it suggests that [clang uses its `libc++` by default](http://stackoverflow.com/questions/25664100/c-all-boost-path-operations-segfault-osx-gcc) while gcc uses `libstdc++`. Is there a way we can force `linux` clang to use the gcc `libstdc++`?

**Comment by peastman** [comment]
`-stdlib=libstdc++`.  See http://clang.llvm.org/docs/CommandGuide/clang.html.

**Comment by jchodera** [comment]
Will try that.

I notice that the python wrappers are built with `gcc/g++`, presumably because this is what anaconda `python` is compiled with. I wonder if this is also an issue.
```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -O3 -I/hbb_shlib/include -I/hbb_shlib/include -fPIC -DMAJOR_VERSION=7 -DMINOR_VERSION=1 -I/anaconda/conda-bld/openmm_1482340194851/work/./include -I/anaconda/conda-bld/openmm_1482340194851/work/./include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/./include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include -I/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/olla/include -I/anaconda/conda-bld/openmm_1482340194851/work/olla/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/olla/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/serialization/include -I/anaconda/conda-bld/openmm_1482340194851/work/serialization/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/serialization/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include/openmm -I/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include/openmm/internal -I/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/python2.7 -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.linux-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
In file included from /anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/OpenMM.h:52:0,
                 from src/swig_doxygen/OpenMMSwig.cxx:6662:
/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/GayBerneForce.h: In constructor 'OpenMM::GayBerneForce::ParticleInfo::ParticleInfo(double, double, int, int, double, double, double, double, double, double)':
/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/GayBerneForce.h:286:19: warning: 'OpenMM::GayBerneForce::ParticleInfo::epsilon' will be initialized after [-Wreorder]
     double sigma, epsilon, sx, sy, sz, ex, ey, ez;
                   ^
/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/GayBerneForce.h:285:9: warning:   'int OpenMM::GayBerneForce::ParticleInfo::xparticle' [-Wreorder]
     int xparticle, yparticle;
         ^
/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/GayBerneForce.h:291:5: warning:   when initialized here [-Wreorder]
     ParticleInfo(double sigma, double epsilon, int xparticle, int yparticle, double sx, double sy, double sz, double ex, double ey, double ez) :
     ^
g++ -pthread -shared -L/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath=/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib,--no-as-needed -L/hbb_shlib/lib -static-libgcc -static-libstdc++ -g -O3 -I/hbb_shlib/include -I/hbb_shlib/include build/temp.linux-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o -L/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-R/anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -lOpenMM -lOpenMMAmoeba -lOpenMMRPMD -lOpenMMDrude -lpython2.7 -o build/lib.linux-x86_64-2.7/simtk/openmm/_openmm.so
[ 53%] Installing OpenMM Python binary module...
OPENMM_LIB_PATH = /anaconda/conda-bld/openmm_1482340194851/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib
OPENMM_INCLUDE_PATH = /anaconda/conda-bld/openmm_1482340194851/work/./include/anaconda/conda-bld/openmm_1482340194851/work/./include/openmm/anaconda/conda-bld/openmm_1482340194851/work/./include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/openmmapi/include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/olla/include/anaconda/conda-bld/openmm_1482340194851/work/olla/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/olla/include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/serialization/include/anaconda/conda-bld/openmm_1482340194851/work/serialization/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/serialization/include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/plugins/amoeba/openmmapi/include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/plugins/rpmd/openmmapi/include/openmm/internal/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include/openmm/anaconda/conda-bld/openmm_1482340194851/work/plugins/drude/openmmapi/include/openmm/internal
```

**Comment by jchodera** [comment]
@peastman: I'm struggling to find any examples of someone linking to clang-compiled libraries with gcc-compiled conda Python on Linux. Without any precedent to work from, I fear my poor understanding of what might be going on with the library compatibilities will lead this to drag on longer without any guarantee we can actually resolve this issue.

We have everything ready for a gcc based release. What do you think about going forward with that, and if we ever do come up with a solution, we can swtiched to clang?

**Comment by peastman** [comment]
Ok, let's go ahead and release that as the beta.  But let's keep working on it and try to have the clang version ready for the release candidate.

**Comment by jchodera** [comment]
Great. I'll get everything updated to build the beta right away, and get that posted today.

If anyone finds ANY examples of someone building conda linux packages using clang-compiled code with a swig interface, that will very much help. We should ask around to see if folks like @rmcgibbo have encountered examples of this.

**Comment by jchodera** [comment]
This seems to be working, so I'm going to give it a try.

Packages will be pushed to `dev` label with `7.2.0` version.

**Pull request merged**
