### PR TITLE
add skorch

### PR DESCRIPTION
**Pull request by cxhernandez**
re: https://github.com/omnia-md/conda-recipes/pull/890/files#r197624338

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like it's [failing](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/396118051#L576) with
```
Error: no such patch: /io/skorch/0001-Compatibility.patch
```

**Comment by cxhernandez** [comment]
Seems like the patch is saved a directory above the `CWD`:

```
Recipes provided (in random order):
['/io/0001-Compatibility.patch', ..., '/io/skorch']
```

Probably want to avoid this behavior in the future in case patches across different packages have the same name

**Comment by cxhernandez** [comment]
woops. placed it in the wrong directory

**Comment by jchodera** [comment]
Qapla'!

**Pull request merged**
