### PR TITLE
add install time warnings for openmm dev

### PR DESCRIPTION
**Pull request by jaimergp**
@peastman @mikemhenry This would add an install-time warning message to the dev snapshots.

Feel free to suggest other message style.

### CODE REVIEW

**Comment by jaimergp** [comment]
[This is how it'll look for the user](https://dev.azure.com/OmniaMD/conda-dev-recipes/_build/results?buildId=552&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=62be5175-061c-5902-0083-624ef9389682&l=4983).

**Comment by peastman** [comment]
That looks good!

**Comment by jchodera** [comment]
This is great!

Should we also include a message on how to get the latest stable build if desired?

**Comment by jaimergp** [comment]
I am assuming if somebody ends up here (undocumented builds), they must know about the stable releases. That said, let me know what kind of text you'd like to add in `post-link.{sh,bat}`.

**Pull request merged**
