### PR TITLE
[WIP] update openmm dev build to use clang 3.8.1 image

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Just a note to myself that I have to figure out how to properly activate the `clang` compiler:

```
-- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
-- Check for working C compiler: /opt/clang/bin/clang
-- Check for working C compiler: /opt/clang/bin/clang -- broken
CMake Error at /anaconda/conda-bld/openmm_1477794742725/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/cmake-3.3/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/opt/clang/bin/clang" is not able to compile a simple test
  program.
  It fails with the following output:
   Change Dir: /anaconda/conda-bld/openmm_1477794742725/work/build/CMakeFiles/CMakeTmp

  Run Build Command:"/usr/bin/gmake" "cmTC_8cf98/fast"
  /usr/bin/gmake -f CMakeFiles/cmTC_8cf98.dir/build.make
  CMakeFiles/cmTC_8cf98.dir/build
  gmake[1]: Entering directory
  `/anaconda/conda-bld/openmm_1477794742725/work/build/CMakeFiles/CMakeTmp'
  Building C object CMakeFiles/cmTC_8cf98.dir/testCCompiler.c.o
  /opt/clang/bin/clang -o CMakeFiles/cmTC_8cf98.dir/testCCompiler.c.o -c
  /anaconda/conda-bld/openmm_1477794742725/work/build/CMakeFiles/CMakeTmp/testCCompiler.c
  Linking C executable cmTC_8cf98

  /anaconda/conda-bld/openmm_1477794742725/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/cmake
  -E cmake_link_script CMakeFiles/cmTC_8cf98.dir/link.txt --verbose=1
  /opt/clang/bin/clang CMakeFiles/cmTC_8cf98.dir/testCCompiler.c.o -o
  cmTC_8cf98 -rdynamic
  /opt/rh/devtoolset-2/root/usr/bin/ld: cannot find crtbegin.o: No such file
  or directory
  /opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgcc
  /opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgcc_s
  clang-3.8: error: linker command failed with exit code 1 (use -v to see
  invocation)
  gmake[1]: *** [cmTC_8cf98] Error 1
  gmake[1]: Leaving directory
  `/anaconda/conda-bld/openmm_1477794742725/work/build/CMakeFiles/CMakeTmp'
  gmake: *** [cmTC_8cf98/fast] Error 2
```

**Comment by mpharrigan** [comment]
~~also need to change this line https://github.com/omnia-md/conda-dev-recipes/blob/master/openmm/build.sh#L9~~ edit: i am dumb

**Comment by mpharrigan** [comment]
in the docker container, trying to compile hello world

```
[root@bdf1e24d7ff2 /]# clang test.c -o test
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgcc
/opt/rh/devtoolset-2/root/usr/bin/ld: cannot find -lgcc_s
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jchodera** [comment]
Oh, I need to change the osx one too!

Any idea what is up with clang? I feel like I'm forgetting something obvious

**Comment by mpharrigan** [comment]
There's lots of reports of this issue. From what I understand, it's from when gcc is installed in a non-standard place or with a non-standard "target triple". 

The file is at `./opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-CentOS-linux/4.8.2/crtbegin.o`

Probably a patch similar to https://reviews.llvm.org/rL213388 would have to be used

**Comment by mpharrigan** [comment]
Workaround! Create a symlink

```
[root@bdf1e24d7ff2 usr]# cd /opt/rh/devtoolset-2/root/usr/lib/gcc
[root@bdf1e24d7ff2 gcc]# ln -s x86_64-CentOS-linux/ x86_64-redhat-linux
[root@bdf1e24d7ff2 gcc]# ls -l
total 0
drwxr-xr-x 3 root root 46 Oct 30 03:41 x86_64-CentOS-linux
lrwxrwxrwx 1 root root 20 Oct 30 03:40 x86_64-redhat-linux -> x86_64-CentOS-linux/

```

**Comment by jchodera** [comment]
Made it a bit farther!

```
[ 34%] Creating OpenMM Python swig input files...
[ 34%] Built target ApiWrappers
Scanning dependencies of target OpenMM
[ 34%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/MonteCarloAnisotropicBarostat.cpp.o
In file included from /anaconda/conda-bld/openmm_1477806881608/work/openmmapi/src/MonteCarloAnisotropicBarostat.cpp:32:
In file included from /anaconda/conda-bld/openmm_1477806881608/work/openmmapi/include/openmm/MonteCarloAnisotropicBarostat.h:36:
In file included from /anaconda/conda-bld/openmm_1477806881608/work/openmmapi/include/openmm/Vec3.h:36:
/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../include/c++/4.8.2/iosfwd:38:10: fatal error: 
      'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
```

**Comment by jchodera** [comment]
Weird. The OpenMM build worked fine when I ran through the steps manually inside the docker image.

**Comment by jchodera** [comment]
How odd. `openmm` seems to build fine when I run through the steps on my local image. Not sure what the discrepancy is.

**Comment by mpharrigan** [comment]
I don't think we should be activating the holy build box stuff (https://github.com/jchodera/conda-dev-recipes/blob/a26ea69683d4e5d6db46a325f7504e6981963028/devtools/docker-build.sh#L4)

Do you include this step when you run locally?

**Comment by jchodera** [comment]
I did, which is why I'm confused. As far as I can tell, the only difference when running locally was that I did a git pull to pull the recipes into the container, rather than using the mount point.

We can certainly try skipping the hbb activation, though!

**Comment by mpharrigan** [comment]
Are you still seeing the same error?

**Comment by jchodera** [comment]
Yep:

```
[ 34%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/MonteCarloAnisotropicBarostat.cpp.o
Generating XML output for class OpenMM::AmoebaMultipoleForce
In file included from /anaconda/conda-bld/openmm_1478065629944/work/openmmapi/src/MonteCarloAnisotropicBarostat.cpp:32:
In file included from /anaconda/conda-bld/openmm_1478065629944/work/openmmapi/include/openmm/MonteCarloAnisotropicBarostat.h:36:
In file included from /anaconda/conda-bld/openmm_1478065629944/work/openmmapi/include/openmm/Vec3.h:36:
/opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../include/c++/4.8.2/iosfwd:38:10: fatal error: 
      'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
```

**Comment by mpharrigan** [comment]
This bit of googling intrigued me, as it's highly related to the workaround we had to do before: http://stackoverflow.com/a/9617178

I don't have time right now to root around the docker image to see if I can reproduce, but will try eventually

**Comment by jchodera** [comment]
Thanks for the lead! I'll have more time to look into this later today.

**Comment by jchodera** [comment]
@peastman : Here's the current procedure I'm using to test/debug:
```bash
# Pull down the docker build box for CUDA 8.0 AMD APP SDK 3.0 with clang 3.8                                                                                                                                                                                                                                                                                                                      
docker run -i -t jchodera/omnia-build-box:cuda80-amd30-clang38 bash                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                  
# configure environment and install miniconda                                                                                                                                                                                                                                                                                                                                                     
set -e                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                  
# Activate Holy Build Box environment.                                                                                                                                                                                                                                                                                                                                                            
#source /hbb_exe/activate                                                                                                                                                                                                                                                                                                                                                                         
#source /hbb_shlib/activate                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                  
# Install miniconda                                                                                                                                                                                                                                                                                                                                                                               
unset PYTHONPATH                                                                                                                                                                                                                                                                                                                                                                                  
set -x                                                                                                                                                                                                                                                                                                                                                                                            
curl -s -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh                                                                                                                                                                                                                                                                                                                  
bash Miniconda3-latest-Linux-x86_64.sh -b -p /anaconda                                                                                                                                                                                                                                                                                                                                            
PATH=/opt/rh/devtoolset-2/root/usr/bin:/opt/rh/autotools-latest/root/usr/bin:/anaconda/bin:$PATH                                                                                                                                                                                                                                                                                                  
conda config --add channels omnia                                                                                                                                                                                                                                                                                                                                                                 
conda install -yq conda-build jinja2 anaconda-client                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                  
# Check out conda dev recipes branch                                                                                                                                                                                                                                                                                                                                                              
git clone https://github.com/jchodera/conda-dev-recipes.git                                                                                                                                                                                                                                                                                                                                       
cd conda-dev-recipes; git checkout openmm; git pull origin openmm ; cd /                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                  
# Build conda package                                                                                                                                                                                                                                                                                                                                                                             
wget -O conda-build-all --no-check-certificate --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all                                                                                                                                                                                                                                                            
chmod u+x conda-build-all                                                                                                                                                                                                                                                                                                                                                                         
./conda-build-all -vvv --dev --force -- /conda-dev-recipes/openmm || true                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                  
# Upload package to anaconda cloud                                                                                                                                                                                                                                                                                                                                                                
anaconda upload --force --label cuda80-clang --channel omnia --user omnia /anaconda/conda-bld/linux-64/openmm-7.1.0-py* || true 
```

**Comment by peastman** [comment]
Thanks.  What are the outstanding problems you wanted me to look into?

**Comment by jchodera** [comment]
The main issue is trying to figure out how to get the `openmm` conda recipe `build.sh` to use `clang` instead of `gcc`. The holy-build-box has scripts that "activate" the gcc build environment (commented out above), and we've installed clang in `/opt/clang` using [this Dockerfile](https://github.com/omnia-md/omnia-build-box/blob/cuda80-amd30-clang38/Dockerfile) but I haven't been able to figure out how to set the environment to ensure `clang` is used for the build.

**Comment by peastman** [comment]
The script fails at this line:

```
cd conda-dev-recipes; git checkout openmm; git pull origin openmm ; cd /
```

with this message:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@a825c3be67ea.(none)')
```

I can set my email, but I'm not clear how this is supposed to work normally.

**Comment by peastman** [comment]
Hitting that error seems to have completely killed the container.  Is that supposed to happen?  I'm suddenly no longer inside the container, and `docker ps` lists nothing.  I don't really know docker very well, so maybe I'm misunderstanding something.  But executing one command that produces an error inside the container shouldn't cause that entire container to be deleted, should it?

**Comment by mpharrigan** [comment]
> `/opt/rh/autotools-latest/root/usr/bin`

This doesn't seem to exist in the container

**Comment by mpharrigan** [comment]
> `git checkout openmm`

This doesn't do anything. Do you mean `git checkout -b openmm origin/openmm`

**Comment by mpharrigan** [comment]
> `git pull origin openmm` 

this should be unnecessary from a fresh checkout, no?

**Comment by mpharrigan** [comment]
The posted script doesn't create the symlink from the above comment. https://github.com/omnia-md/conda-dev-recipes/pull/53#issuecomment-257130199

**Comment by mpharrigan** [comment]
Fixed the "bits/c++config.h" issue by a similar symlink:

```
cd /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2
ln -s x86_64-CentOS-linux/ x86_64-redhat-linux
```

**Comment by mpharrigan** [comment]
I ended up sourcing `/hbb_shlib/activate` while troubleshooting. I'm not sure if this step is required. At the very least, it should set the flag to statically link libstdc++ (which we need for this binary to be portable)

**Comment by mpharrigan** [comment]
Everything compiles, but getting a ton of link errors https://gist.github.com/mpharrigan/a618f3a05951a1f319ecd036fb68f835

**Comment by jchodera** [comment]
> Hitting that error seems to have completely killed the container. Is that supposed to happen? 

Unfortunately, a command that returns an exit code kills the docker container. I find this supper annoying. 

More info on this here: https://blog.codeship.com/ensuring-containers-are-always-running-with-dockers-restart-policy/

**Comment by jchodera** [comment]
> Everything compiles, but getting a ton of link errors 

That's exactly what I was running into as well. Apologies for not being more explicit.

**Comment by mpharrigan** [comment]
> That's exactly what I was running into as well. Apologies for not being more explicit.

There were a lot of things I had to change to get to this point (see above comments). Were you really using that script verbatim?

>>    Hitting that error seems to have completely killed the container. Is that supposed to happen?

> Unfortunately, a command that returns an exit code kills the docker container. I find this supper annoying

If you're playing around interactively, don't use `set -e` at the beginning and it should be fine

**Comment by mpharrigan** [comment]
I was able to get a "successful" compilation by disabling OPENMM_BUILD_CUDA_TESTS, OPENMM_BUILD_EXAMPLES, and OPENMM_BUILD_OPENCL_TESTS

**Comment by mpharrigan** [comment]
Another thing I noticed: the cuda runtime compiler plugin isn't being built because the container doesn't seem to include `CUDA_nvrtc_LIBRARY` or it's associated headers. Don't we want this?

**Comment by mpharrigan** [comment]
Other note: setting CMAKE_CXX_FLAGS_RELEASE removes the `-O3` flag which is there by default, which we probably really want. The nvidia include spec should be added to `CMAKE_CXX_FLAGS`

**Comment by jchodera** [comment]
> There were a lot of things I had to change to get to this point (see above comments). Were you really using that script verbatim?

I was honestly just working interactively and trying to take notes. 

> Other note: setting CMAKE_CXX_FLAGS_RELEASE removes the -O3 flag which is there by default, which we probably really want. The nvidia include spec should be added to CMAKE_CXX_FLAGS

This is in the conda recipe? I wonder if this is responsible for some of the speed difference we see with the current gcc-build conda package.

**Comment by mpharrigan** [comment]
> I was honestly just working interactively and trying to take notes.

Ah, ok. I'm not going crazy :)

> This is in the conda recipe?

https://github.com/jchodera/conda-dev-recipes/blob/openmm/openmm/build.sh#L15

**Comment by jchodera** [comment]
(Redacted; wrong recipe)

**Comment by peastman** [comment]
> I wonder if this is responsible for some of the speed difference we see with the current gcc-build conda package.

When I ran the tests described at https://github.com/pandegroup/openmm/issues/1613#issuecomment-254294637, I wasn't using conda builds.  That was compiling from source myself, changing nothing except the compiler.

Could you post a complete script that works as far as you've gotten it to work so far?  There's a lot going on in the one you posted that I don't completely understand, and then a lot of comments suggesting various changes to it, which I don't know whether they're correct or not.

**Comment by jchodera** [comment]
> Another thing I noticed: the cuda runtime compiler plugin isn't being built because the container doesn't seem to include CUDA_nvrtc_LIBRARY or it's associated headers. Don't we want this?

Here's the [Dockerfile](https://github.com/omnia-md/omnia-build-box/blob/cuda80-amd30/Dockerfile) that install CUDA into the container. I'm honestly surprised we can install CUDA at all into a CentOS 5 image, but we must be missing the CUDA nvrtc package. Any ideas which RPM we're missing?

**Comment by jchodera** [comment]
I'm guessing it's these three:
```
(27/38): cuda-nvrtc-8-0-8.0.44-1.x86_64.rpm | 9.1 MB 00:00:01 
(28/38): cuda-nvrtc-dev-8-0-8.0.44-1.x86_64.rpm | 15 kB 00:00:00 
(29/38): cuda-runtime-8-0-8.0.44-1.x86_64.rpm | 6.0 kB 00:00:00 
```

**Comment by mpharrigan** [comment]
Fixed the linker problems. `hbb_shlib` sets `CFLAGS` to contain `-fvisibility=hidden`, which breaks everything. We should

1) try building without ever sourcing hbb_shlib/activate. We'd need to set LDFLAGS ourselves, probably

2) remove -fvisibilty from CMAKE_C(xx)_FLAGS

**Comment by jchodera** [comment]
> try building without ever sourcing hbb_shlib/activate. We'd need to set LDFLAGS ourselves, probably

The [`docker-build.sh` script](https://github.com/omnia-md/conda-recipes/blob/master/devtools/docker-build.sh) currently sources `/hbb_exe/activate`. Will that cause problems? Is it something we can undo within the `build.sh` script, rather than having to retool `docker-build.sh`?

**Comment by jchodera** [comment]
I'm trying to rebuild the `omnia-build-box:cuda80-amd30` docker image right now with the `nvrtc` and `runtime` additions. Will let you know how that goes.

**Comment by mpharrigan** [comment]
> Will that cause problems? Is it something we can undo within the build.sh script, rather than having to retool docker-build.sh?

Yes, let's just reset CFLAGS and CXXFLAGS

**Comment by peastman** [comment]
You two seem to have this under control, so I'm going to move to working on the Windows builds.  I'll probably end up building by hand, the same way I have for past releases.  But we really need to start moving toward something more automated, so I'm going to at least start looking into that.

Preliminary support for running Windows inside Docker was recently announced: https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container.  But it's still in beta, and as far as I can tell it requires that Docker itself is running on Windows.  I think we probably want something more stable than that.

Vagrant looks like another possibility, so that's probably what I'll try first.  Anyone have experience using Vagrant to build Windows VMs?  Does that seem like a good approach?  Are there any other options I should be considering?

**Comment by jchodera** [comment]
I've added the CUDA runtime to the `Dockerfile` for `cuda80-amd30` here:
https://github.com/omnia-md/omnia-build-box/blob/cuda80-amd30/Dockerfile#L36-L38

The image is currently queued to rebuild:
https://hub.docker.com/r/jchodera/omnia-build-box/builds/

After that, I'll regenerate the clang image locally and push the update.

**Comment by jchodera** [comment]
I've updated the `cuda80-amd30-clang38` docker image with the CUDA runtime additions above to install:
```
(27/38): cuda-nvrtc-8-0-8.0.44-1.x86_64.rpm | 9.1 MB 00:00:01 
(28/38): cuda-nvrtc-dev-8-0-8.0.44-1.x86_64.rpm | 15 kB 00:00:00 
(29/38): cuda-runtime-8-0-8.0.44-1.x86_64.rpm | 6.0 kB 00:00:00 
```
Hopefully, that's what we needed!

**Pull request closed without merging**
