### PR TITLE
Multi-CUDA build testing

### PR DESCRIPTION
**Pull request by jchodera**
This tests some basic infrastructure for multi-CUDA OpenMM builds.

### CODE REVIEW

**Comment by jchodera** [comment]
@Lnaden : Any idea what is going on here?
https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/397004134#L7599-L7601

**Comment by Lnaden** [comment]
On quick glance it looks like cuda75 py27 variant and openmm dont work. There is a cuda info packages command but im on mobile so I cant look right now. I will check on train though

**Comment by jchodera** [comment]
@Lnaden : None of the CUDA x  python combinations succeeded, so I imagine something else is going on here.

**Comment by jchodera** [comment]
Notably, the builds all completed successfully---the testing stage of conda-build seemed to fail for an inscrutable reason that may have something to do with the [custom build string](https://github.com/omnia-md/conda-dev-recipes/pull/136/files#diff-7844bc65941f15646bf4df7d3c673410R13) or [feature requirement](https://github.com/omnia-md/conda-dev-recipes/pull/136/files#diff-7844bc65941f15646bf4df7d3c673410R15).

In case the feature requirement is the culprit, I'm moving the `cudaXY` package builds to `conda-recipes`:
https://github.com/omnia-md/conda-recipes/pull/892

**Comment by jchodera** [comment]
@lnaden: Now I'm super confused:
```
Can't build /io/openmm due to environment creation error:
  - openmm 7.3.0 py27_cuda75_0
  - cuda75
  - openmm 7.3.0 py27_cuda75_0
  - @cuda75
  - cuda75
```

**Pull request merged**
