### PR TITLE
Check Homebrew-cask and basictex paths

### PR DESCRIPTION
**Pull request by Lnaden**
This PR is an exact copy of omnia-md/conda-recipes#786 to fix the exact same issue

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

**Comment by Lnaden** [comment]
OSX builds will fail for a while because the Homebrew-cask for basictex points to a version of the file not hosted on the CTAN mirrors as of a few days ago. If I get time before they find and get to it, I'll try to make a PR on there to fix it

**Comment by Lnaden** [comment]
Someone else updated the package, now we just have to hope the mirrors it targets finally completes a download.

**Comment by Lnaden** [comment]
Okay... Now I think the MacTex/BasicTeX distributions hate me. All the mirrors seem to just timeout when they try to download the version of BasicTex, but none of them host the older versions either. And I can't find any stable older versions of it anywhere (i.e. caskroom/homebrew-versions does not have it). If the file was not 70+ MB, I would say just host a stable version ourselves

**Comment by Lnaden** [comment]
I merged this because it finally worked, but who know how long it will be stable for. We're at the mercy of the basictex mirrors for now

**Comment by jchodera** [comment]
Can we mirror it ourselves?

**Comment by Lnaden** [comment]
Again, its >70MB, I'm not sure where we would host it in a long term stable manor, and even then, we are at the mercy of the CTAN mirrors after that for the TeX package versions.

**Pull request merged**
