### PR TITLE
Update to conda-forge based linux anvil

### PR DESCRIPTION
**Pull request by Lnaden**
This update brings the dev channel to CentOS6 in line with omnia-md/conda-recipes#761

`conda-forge` is now a channel requirement for conda as well

Supersedes and closes #53

### CODE REVIEW

**Comment by jchodera** [comment]
It looks like these two lines cause the `osx` build to fail to install
```
conda config --set channel_priority false;
conda config --add channels conda-forge;
```
since commenting them out allows the `osx` builds to succeed and pass travis.

Here are the packages retrieved during success:
```
BUILD START: openmm-7.3.0-py27_0
The following NEW packages will be INSTALLED:
    alabaster:                     0.7.10-py27_0      
    babel:                         2.4.0-py27_0       
    bzip2:                         1.0.6-3            
    cmake:                         3.6.3-0            
    curl:                          7.52.1-0           
    docutils:                      0.13.1-py27_0      
    expat:                         2.1.0-0            
    fftw3f:                        3.3.3-1       omnia
    funcsigs:                      1.0.2-py27_0       
    imagesize:                     0.7.1-py27_0       
    jinja2:                        2.9.6-py27_0       
    latexcodec:                    1.0.1-py27_0  omnia
    libiconv:                      1.14-0             
    libxml2:                       2.9.4-0            
    libxslt:                       1.1.29-0           
    lxml:                          3.7.3-py27_0       
    markupsafe:                    0.23-py27_2        
    mkl:                           11.3.3-0           
    mock:                          2.0.0-py27_0       
    ncurses:                       5.9-10             
    numpy:                         1.10.4-py27_2      
    openssl:                       1.0.2k-1           
    oset:                          0.1.3-py27_1  omnia
    pbr:                           1.10.0-py27_0      
    pcre:                          8.39-1             
    pip:                           9.0.1-py27_1       
    pybtex:                        0.18-py27_0   omnia
    pybtex-docutils:               0.2.1-py27_1  omnia
    pygments:                      2.2.0-py27_0       
    python:                        2.7.13-0           
    pytz:                          2017.2-py27_0      
    pyyaml:                        3.12-py27_0        
    readline:                      6.2-2              
    requests:                      2.13.0-py27_0      
    setuptools:                    27.2.0-py27_0      
    six:                           1.10.0-py27_0      
    snowballstemmer:               1.2.1-py27_0       
    sphinx:                        1.5.1-py27_0       
    sphinxcontrib-autodoc_doxygen: 0.3.2-py27_0  omnia
    sphinxcontrib-bibtex:          0.3.2-py27_0  omnia
    sphinxcontrib-lunrsearch:      0.2-py27_1    omnia
    sqlite:                        3.13.0-0           
    swig:                          3.0.8-0       omnia
    tk:                            8.5.18-0           
    wheel:                         0.29.0-py27_0      
    xz:                            5.2.2-1            
    yaml:                          0.1.6-0            
    zlib:                          1.2.8-3     
```

**Comment by jchodera** [comment]
Adding `conda-forge`, it does not build. These packages are used.
```
    alabaster:                     0.7.10-py27_0                 conda-forge
    babel:                         2.4.0-py27_0                             
    blas:                          1.1-openblas                  conda-forge
    boost:                         1.63.0-py27_5                 conda-forge
    boost-cpp:                     1.63.0-2                      conda-forge
    bzip2:                         1.0.6-1                       conda-forge
    ca-certificates:               2017.1.23-1                   conda-forge
    certifi:                       2017.4.17-py27_0              conda-forge
    cmake:                         3.7.1-4                       conda-forge
    curl:                          7.52.1-0                      conda-forge
    docutils:                      0.13.1-py27_0                 conda-forge
    expat:                         2.1.0-2                       conda-forge
    fftw3f:                        3.3.3-1                       omnia      
    icu:                           58.1-1                        conda-forge
    imagesize:                     0.7.1-py27_0                  conda-forge
    jinja2:                        2.9.6-py27_0                             
    jsoncpp:                       0.10.6-1                      conda-forge
    latexcodec:                    1.0.4-py27_0                  conda-forge
    libarchive:                    3.2.1-2                       conda-forge
    libgfortran:                   3.0.0-0                       conda-forge
    libiconv:                      1.14-4                        conda-forge
    libuv:                         1.11.0-0                      conda-forge
    libxml2:                       2.9.4-4                       conda-forge
    libxslt:                       1.1.29-3                      conda-forge
    lxml:                          3.7.3-py27_0                  conda-forge
    markupsafe:                    0.23-py27_1                   conda-forge
    ncurses:                       5.9-10                        conda-forge
    numpy:                         1.10.4-py27_blas_openblas_205 conda-forge [blas_openblas]
    openblas:                      0.2.19-2                      conda-forge
    openssl:                       1.0.2k-0                      conda-forge
    oset:                          0.1.3-py27_1                  omnia      
    pcre:                          8.39-0                        conda-forge
    pip:                           9.0.1-py27_0                  conda-forge
    pybtex:                        0.18-py27_0                   omnia      
    pybtex-docutils:               0.2.1-py27_1                  omnia      
    pygments:                      2.2.0-py27_0                  conda-forge
    python:                        2.7.13-0                      conda-forge
    pytz:                          2017.2-py27_0                 conda-forge
    pyyaml:                        3.12-py27_1                   conda-forge
    readline:                      6.2-0                         conda-forge
    requests:                      2.13.0-py27_0                 conda-forge
    setuptools:                    33.1.1-py27_0                 conda-forge
    six:                           1.10.0-py27_1                 conda-forge
    snowballstemmer:               1.2.1-py27_0                  conda-forge
    sphinx:                        1.5.5-py27_0                  conda-forge
    sphinxcontrib-autodoc_doxygen: 0.3.2-py27_0                  conda-forge
    sphinxcontrib-bibtex:          0.3.2-py27_0                  omnia      
    sphinxcontrib-lunrsearch:      0.2-py27_1                    omnia      
    sqlite:                        3.13.0-1                      conda-forge
    swig:                          3.0.8-0                       conda-forge
    tk:                            8.5.19-1                      conda-forge
    wheel:                         0.29.0-py27_0                 conda-forge
    xz:                            5.2.2-0                       conda-forge
    yaml:                          0.1.6-0                       conda-forge
    zlib:                          1.2.11-0                      conda-forge
```
I notice swig 3.0.8 is being pulled from conda-forge. I'll see if I can override that.

**Comment by jchodera** [comment]
I'm wondering if something might silently be failing in [OpenMM's `setup.py`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/setup.py#L233-L246), possibly due to the way it is [called by CMake](https://github.com/pandegroup/openmm/blob/master/wrappers/python/CMakeLists.txt).

My next experiment is to try to build locally to see if the `version.py` is even being generated, or `setup.py` is being called at all.

**Comment by jchodera** [comment]
I *do* notice [an error line](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/224827165#L4778) amidst the build output that I seem to have missed before:
```
error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.9" during configure
```
Not sure where that is coming from...

**Comment by jchodera** [comment]
It looks like conda-build [overrides `MACOSX_DEPLOYMENT_TARGET` to 10.7](https://github.com/conda/conda-build/pull/1561) unless an environment variable is set inside the conda build recipe!

**Comment by jchodera** [comment]
I've at least fixed the `MACOSX_DEPLOYMENT_TARGET` inconsistency, but I haven't yet figured out what is causing the problem with the `install_lib` (and other `setup.py` install steps) being skipped on `osx`.

**Comment by Lnaden** [comment]
After doing some more examination of the logs, I think the problem we have is actually the error you pointed out, @jchodera. Comparing the OSX Python 3.4 and Python 3.5 build logs, I see the following:

Python 3.4: configures against macosx-*10.6* for some reason. `creating build/lib.macosx-10.6-x86_64-3.4` but I'm guessing since that would be forward compatible with new compilers it does not throw the error

Python 3.5: The python build is configured against macosx-10.9, but then the min version is 10.7. Since this is not backwards compatible, the Python build halts right there. 

Now the question is how to get the build to build against a specific version during both config and build.

**Comment by jchodera** [comment]
According to [this PR](https://github.com/conda/conda-build/pull/1561), setting the environment variable `MACOSX_DEPLOYMENT_TARGET` allows us to override the target, but I realize 
* I'm not sure which version of `conda-build` this was released in
* I'm not sure if that environment variable should go in the `build.sh` script (like I've put it) or into the `osx-build.sh` environment
* Even now that I have restored the suggested deployment target to 10.7 everywhere, it still is skipping `install_lib` and friends

**Comment by Lnaden** [comment]
And then to make things more weird, the `MACOSX_DEPLOYMENT_TARGET=10.7` is set on both and the `clang` calls both have `-mmacosx-version-min=10.7` (which I assume its reading from the env variable)

**Comment by Lnaden** [comment]
Adding to this, on the successful builds on the `master` branch before this PR, the Python 2.7, 3.5, and 3.6 builds use the macosx10.7 SDK to configure itself, whereas the 3.4 build uses the macosx10.6 to configure. They both then build on 10.7.

So the question then is, where is this 10.9 sdk randomly coming from and why does it only show up with conda-forge?

**Comment by jchodera** [comment]
Also, uh-oh: Looks like `conda-build` 3.0 is on the horizon:
https://github.com/conda/conda-build/releases/tag/3.0.0beta0

**Comment by Lnaden** [comment]
> Looks like conda-build 3.0 is on the horizon:

Yes, and that will also be a major API break, but there is nothing saying we have to have the omnia related builds go to that, we can stay pinned to a version before 3.0 if it changes too much. But we can focus on this mac issue for now and worry about that one later.

**Comment by jchodera** [comment]
I think you're on the right track with this `MACOSX_DEPLOYMENT_TARGET` thing though. Good catch.

**Comment by Lnaden** [comment]
Okay I added some thing to the wrong issue. see
* [here](https://github.com/omnia-md/conda-recipes/pull/761#issuecomment-296311792)
* [here](https://github.com/omnia-md/conda-recipes/pull/761#issuecomment-296691110)
* [here](https://github.com/omnia-md/conda-recipes/pull/761#issuecomment-296691225)
* [here](https://github.com/omnia-md/conda-recipes/pull/761#issuecomment-296692730)
* and [here](https://github.com/omnia-md/conda-recipes/pull/761#issuecomment-296693700)

**Comment by Lnaden** [comment]
> Are all the conda-forge python versions built with 10.7 or earlier? If so, could we just

The `conda-forge` most recent Python 2.7, 3.5, and 3.6 are built against macosx-10.9, Python 3.4 (which we should drop support for) is built against 10.6.

The `default` channel Pythons appear to be built against 10.7 (27, 35, and 36) and 10.6 (34). 

We also cannot pin the top level python executable to a specific version/build, we would need to find the maximum version *on both channels, for all python versions* which meets the requirements and pin OpenMM to that since the build environment gets its own python for each build. 

We may be able to do something in the `setup.py` script in line with [PEP508](https://www.python.org/dev/peps/pep-0508/) to figure out a solution, but that sounds painful and probably does not extend to `conda` requirements.

**Comment by Lnaden** [comment]
And following up, I don't think there is anyway to point Python's internal MACOSX_DEPLOYMENT_TARGET to a lower target than it was built against.

**Comment by jchodera** [comment]
If we change the deployment target to 10.9 everywhere, would that work?

Odd about conda forge using 10.9, but we are stuck with that it seems

**Comment by Lnaden** [comment]
If we did change the deployment target, that would change the oldest version of `OSX` that OpenMM could be deployed on, and we cannot do that unless we cut a new release. For the dev channel, it would be okay. But for the main channel, I don't think we could do that.

Anaconda themselves are still building against OSX 10.7 as a minimum, but it appears the conda-forge is building against 10.9. I am actually going to raise an issue with the conda-forge python-feedstock to request they fall back in line with anaconda, but I don't know how well that will work since all their builds fire off from `travis`, which has the oldest xcode version of 6.4, which only has macosx10.9, so I'm *not sure they even can* build against osx 10.7

**Comment by Lnaden** [comment]
@peastman with respect to the issues above, how viable is it to update OpenMM to rely on osx 10.9 as a min version for future releases?

**Comment by jchodera** [comment]
@lnaden: xcode6.4 includes the 10.7 framework. See the Travis docs for that image.

Also, please see the openmm issue I raised about updating the minimum osx compatibility version for conda packages.

I think we should move ahead with trying to make 10.9 work for the dev builds now.

**Comment by Lnaden** [comment]
> Xcode6.4 includes the 10.7 framework. See the Travis docs for that image.

I already did, it does not include 10.7. 10.9 is the earliest it has.

Taken directly from [the travis-ci site](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4) in its entirety
```Xcode 6.4 #

Xcode 6.4 is available by adding osx_image: xcode6.4 to your .travis.yml.

Please note that this image is no longer updated and will be retired on Friday, January 20th

Our Xcode 6.4 images have the following SDKs preinstalled:

macosx10.9
macosx10.10
iphoneos8.4
iphonesimulator8.4
The Xcode 6.4 image also comes with the following simulators:
```

**Comment by jchodera** [comment]
I had totally misread that! This explains the conda-forge min version, but doesn't explain how we were able to actually build 10.7 on Travis earlier...

**Comment by Lnaden** [comment]
> how we were able to actually build 10.7 on Travis earlier

Because the versions of Python on the `default` channel for anaconda are built against [OSX 10.7 at the latest](https://github.com/ContinuumIO/anaconda-issues/issues/413#issuecomment-132830532) (they don't use Travis to compile their builds I would guess). So when we built OpenMM on travis, the Pythons that were fetched were built against the older OSX and so could build with our min version of 10.7 for OpenMM. You can see this in the `master` branch builds where the builds after the `make -j2 install PythonInstall` and the `PythonInstall` target are loaded into `macosx-10.6` (for python 34) and `macosx-10.7` (other python vers) folders for build, then compiled later on.

If we had set the min mac version to 10.6 of OpenMM, we would see the same problem we are having on conda-forge. The issue is that conda-forge python and anaconda default python are compiled against different minimum macosx targets.

**Comment by Lnaden** [comment]
I'll change the min version here, but that alone won't fix the problem since [the version is hard coded](https://github.com/pandegroup/openmm/blob/fbf193fe366dbd1a9c39eec754f737b42d24acac/wrappers/python/setup.py#L195) in openmm's setup.py file. We should also determine *which* version we are going to from [the discussion on the openmm site](https://github.com/pandegroup/openmm/issues/1791) so we dont have to do this again when/if `xcode6.4` up and disappears.

**Comment by peastman** [comment]
I'd be ok with requiring 10.9.  It's over three years old, and there have probably been two new versions released since the last time we updated the minimum required version.

**Comment by Lnaden** [comment]
Okay, the follow up question is do we go to 10.9 or 10.11? I have asked the Travis people to give me a better timeline on the xcode6.4 retirement (min version 10.9) and see when we have to go to xcode7.3.1 (min/only version 10.11). We can also continue this discussion on the actual [OpenMM issue](https://github.com/pandegroup/openmm/issues/1791) where it may be more relevant.

**Comment by jchodera** [comment]
We go to 10.9 to get this working immediately and harmonize with `conda-forge`.

Henceforth, we really have to sync up with `conda-forge` at every step of the way to keep things compatible.

**Comment by Lnaden** [comment]
We dont have to go with 10.9, we only have to have a minimum of 10.9 to be in sync. We can use minimums greater than the python minimum, just not the other way around.

**Comment by peastman** [comment]
10.11 was released less than two years ago.  We need to keep supporting older versions than that.

**Comment by jchodera** [comment]
Let's go with 10.9.

**Comment by Lnaden** [comment]
Like I said, I sent an email to the Travis people to see what the timeline on losing access to the macosx10.9 image from Xcode6.4 (remember that they said it was suppose to retire in this recently passed January). Once they do that, the oldest version of the macosx that their Xcode will have it in is 10.11. We will need to have a fix of some kind if we want to keep supporting 10.9 when that happens.

Their turn around has been about 1 day in the past

**Comment by jchodera** [comment]
Let's go with 10.9 for now. We have to get things in sync with `conda-forge`, so if they're using it, we should see if it can work for us too.

We can make longer-term plans to deal with travis deprecation in the slightly longer term, but this also has to happen in sync with `conda-forge` going forward.

**Comment by Lnaden** [comment]
I have bumped the min version of the osx builds. Now fixing the linux builds are a bit tricker. The error appears to be thrown [here](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225330072#L2202-L2269) in the travis logs and it looks like a compiler error. The problem is that this error does not appear on the working `master` version or on the new `omnia-linux-anvil` on the main `conda-recipes` repo. 

So this problem was either introduced:
* since 7.1.0 and the old holy build box was flagged to ignore it (doubtful since there were no compiler flags set in the holy-build-box fixes)
* Is now an error based on the difference in compilers between the the conda-recipes and the conda-dev-recipes. It is still possible this was introduced since 7.1.0, but hard to tell. 

Here are the differences between the 7.1.0 and the dev 7.3.0 in the package list:

| package | conda-recipes (works) | conda-dev-recipes (fails) |
|:-:|:--------------:|:-------------------:|
| blas |  | blas 1.1-openblas | 
| libgfortran |  | 3.0.0-1 |
| numpy |  | 1.10.4-pyXX_blas_openblas_205 |
| openblas |  | 0.2.19-2 |

Any thoughts? 

I also have the differences between the live version which does work and the PR version here, but its a much longer list due to different compiler sources (same compiler though).

**Comment by Lnaden** [comment]
On the upside though, the OSX builds are fixed

**Comment by jchodera** [comment]
I think the actual compiler error is [here](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225330072#L2249-L2272):
```
In file included from /opt/conda/conda-bld/openmm_1493060017741/work/openmmapi/src/AndersenThermostat.cpp:33:
In file included from /opt/conda/conda-bld/openmm_1493060017741/work/openmmapi/include/openmm/internal/AndersenThermostatImpl.h:35:
In file included from /opt/conda/conda-bld/openmm_1493060017741/work/openmmapi/include/openmm/internal/ForceImpl.h:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/vector:65:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:258:15: error: 
      no matching function for call to 'forward'
      : _Base(std::forward<_Base>(__x)) { }
              ^~~~~~~~~~~~~~~~~~~
/opt/conda/conda-bld/openmm_1493060017741/work/openmmapi/include/openmm/internal/ForceImpl.h:105:16: note: 
      in instantiation of member function 'std::vector<std::pair<int, int>,
      std::allocator<std::pair<int, int> > >::vector' requested here
        return std::vector<std::pair<int, int> >(0);
               ^
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/move.h:51:5: note: 
      candidate function [with _Tp = std::_Vector_base<std::pair<int, int>,
      std::allocator<std::pair<int, int> > >] not viable: no known conversion
      from 'std::vector<std::pair<int, int>, std::allocator<std::pair<int, int>
      > >' to 'typename std::identity<_Vector_base<pair<int, int>,
      allocator<pair<int, int> > > >::type &&' (aka
      'std::_Vector_base<std::pair<int, int>, std::allocator<std::pair<int, int>
      > > &&') for 1st argument
    forward(typename std::identity<_Tp>::type&& __t)
    ^
2 errors generated.
make[2]: *** [CMakeFiles/OpenMM.dir/openmmapi/src/AndersenThermostat.cpp.o] Error 1
make[1]: *** [CMakeFiles/OpenMM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Looks like a STL error, and it looks like `gcc` is (incorrectly) being used to compile OpenMM instead of `clang`.

**Comment by mpharrigan** [comment]
I think clang uses gcc's c++ library. I also think with conda-forge you have to list `toolchain` as a dependency to get their spiffy gcc version > 4.4 . might be worth a shot

**Comment by Lnaden** [comment]
The problem with that argument is that we get this lines at the start
```
-- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
```
so I would guess that its clang using the gcc compiled libs, but I dont actually know myself.

**Comment by Lnaden** [comment]
or what @mpharrigan said.

If we need to specify `toolchain`, then why does the version compiling the 7.1.0 version on the main `conda-recipes` repo not throw the same error?

I'll give it a shot though!

**Comment by mpharrigan** [comment]
because peter recently started using c++11 features

**Comment by Lnaden** [comment]
That did not appear to work. @mpharrigan you are most likely right that its a gcc version/library issue, but I can't figure out what would need to be done from here.

**Comment by Lnaden** [comment]
Okay, after some more digging, this looks to be a problem with the `openblas` package that comes in from `numpy` based on my reading of [this thread from the numpy conda-forge feedstock](https://github.com/conda-forge/numpy-feedstock/issues/15#issuecomment-225322659)

Now lets see how to fi it

**Comment by Lnaden** [comment]
We may also need to modify the docker build image to get the right libgfortran based on [what the scipy people did to overcome a similar openblas problem](https://github.com/conda-forge/scipy-feedstock/pull/3/files) (this pr also linked to the previous issue)

**Comment by Lnaden** [comment]
Okay, this is also confusing. The GCC throwing the errors against is version 4.4.7, but the system gcc from the top is actually 4.8.4. So now I am deeply confused.

**Comment by Lnaden** [comment]
The GCC 4.4.7 is the version that comes stock with CentOS6, but that should be overwritten by the GCC that comes with the devtoolset-2 from the [conda-forge docker image](https://github.com/conda-forge/docker-images/blob/5ecdc153c7c5116cf93c63548e521fd8f06152d0/linux-anvil/Dockerfile#L40-L41). And the gcc that from [start of the travis build](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225601777#L266-L268) is in fact 4.8.4.

I am running some more debugging to figure out where the wrong gcc libs get linked. Any input from others as to what to look at would help though as my knowledge of compilers and libraries is pretty minimal

**Comment by Lnaden** [comment]
So the `cc` and `c++` are correctly mapped to the ones from `devtools-2`
```
$ gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

$ echo $CC
gcc

$ echo $CXX
g++

$ readlink -f `which cc`
/opt/rh/devtoolset-2/root/usr/bin/gcc

$ readlink -f `which c++`
/opt/rh/devtoolset-2/root/usr/bin/c++
```

So is it the `clang` from the `clangdev` package that is using the CentOS6 libs? Is there a flag I need to set for that?

**Comment by jchodera** [comment]
Try feeding `clang` this argument:
```
--gcc-toolchain=<value> Use the gcc toolchain at the given directory
```
[These docs](http://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library) may be relevant.

**Comment by Lnaden** [comment]
@peastman @mpharrigan Could use some help figuring this particular bug out. 

Short version: How do I get the c++ compiler to target the compiled c++ standard libs from the correct gcc version.

Without making changes, cmake uses `clang` and `clang++` as compilers, but the c++ libraries appear to link against the CentOS 6 gcc which [causes STL errors](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225617460#L2246), probably from the C++11 as @mpharrigan pointed out. The CentOS 6 version is the 4.4.7 which is missing features. This should not be happening because the `gcc` and `g++` that is installed from the `devtoolset-2` of the `linux-anvil` is 4.8.2  as seen [in the opening of Travis](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225617460#L461-L471)

Exporting the `CC` and `CXX` variables to be `gcc` and `g++` found in path [does not work either](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225639427#L491-L493) and it still fetches the system gcc libs.

I can set the [`--gcc-toolchain=/opt/rh/devtoolset-2/root/usr/`](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225657932#L507-L510) in `CFLAGS` and `CXXFLAGS` to target where the `devtoolset` is installed on the Docker image, but then that causes a problem during the Python install where that flag gets [passed to the gcc of python's setup.py](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225657932#L3546-L3548) and is unrecognized. I also worry that it means `clang` would be used for the c++ compile, and gcc for the python which I'm not sure is intentional.

Finally I have tried to [export CC and CXX](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225667861#L482-L484) to point directly at the `devtoolset-2` binaries, then add the additional CMAKE flag of [`CMAKE_FLAGS+=' -DCMAKE_CXX_LINK_FLAGS=-Wl,-rpath,/opt/rh/devtoolset-2/root/usr/lib64'`](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225667861#L514) as part of the OpenMM build script, but that just has the same problem and gets the CentOS 6 stock versions.

I'm at the limit of my compiler knowledge here and am just taking very loosely informed guesses at this point. Any ideas?

**Comment by mpharrigan** [comment]
The cc and cxx stuff is all red herring. clang needs to know where libstdc++ and its headers are. I think @jchodera 's clang flag is the best lead. The problem identified seems solvable. Put in something to remove that cflag before python install. Or instead of using cflags, use the cmake C_COMPILER_OPTIONS or whatever it's called. I can't imagine those get used during python setup.py install

**Comment by peastman** [comment]
Is the problem really from using the wrong compiler?  Or is it just that you need to tell it which standard library (libstdc++ or libc++) to use?  I believe the compiler has a command line argument you can use for that.

**Comment by Lnaden** [comment]
Its probably pointing it at the standard library. I know very little with respect to compilers and flags, would that be just as simple as adding a `-L/path/to/lib64` to the `CFLAGS` and `CXXFLAGS` variables?

**Comment by mpharrigan** [comment]
As far as I can tell, using the `--gcc-toolchain` argument fixed the problem. Do that!!

**Comment by Lnaden** [comment]
> Or is it just that you need to tell it which standard library (libstdc++ or libc++) to use?

To be more clear, the problem is not that its the wrong standard library, its the *wrong version* of the standard library. Its trying to find standard library files in the CentOS 6 system gcc library of 4.4.7, when it should be looking instead for the standard library in the gcc 4.8.4 library that came from `devtoolset-2`

> As far as I can tell, using the --gcc-toolchain argument fixed the problem. Do that!!

It fixes the C++ part, but then the PythonCompile [fails](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/225657910#L3537-L3538) because the `--gcc-toolchain` flag is passed on the GCC as the compiler for the Python part and fails since gcc does not know what that flag is. I'm not sure that behavior is right either; i.e. should `python setup.py install` use gcc even though the c++ used clang? Did we instead use the GCC compiler for the c++ part on accident even though it said it found and was using the `clang` compiler at the top?

**Comment by mpharrigan** [comment]
> i.e. should python setup.py install use gcc even though the c++ used clang? Did we instead use the GCC compiler for the c++ part on accident even though it said it found and was using the clang compiler at the top?

This is an orthogonal question. Pretty sure we've always been building the python extensions with gcc. This might even be necessary because python itself was built with gcc but idk

> PythonCompile fails because the --gcc-toolchain flag is passed on the GCC as the compiler for the Python part

This seems like a solvable problem. I'd try these things (stopping when one works)

1. move the `gcc-toolchain` flag to a cmake option and hope it doesn't get forwarded during python install
2. add a line to the build script to re-set cflags before python install
3. add something to setup.py to intercept that argument and throw it away during extension compilation

**Comment by peastman** [comment]
Clang and gcc are binary compatible with each other.  That shouldn't matter.

There are two main places where binary compatibility is an issue.  One is that clang and gcc use different implementations of the C++ standard library by default.  See https://libcxx.llvm.org/.  The other is that gcc 5.1 introduced changes to its ABI that broke binary compatibility.  See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html.  Clang added support for that in a recent version, I think 3.8.

**Comment by Lnaden** [comment]
Okay. I added `CMAKE_FLAGS+=" -DCMAKE_CXX_FLAGS=--gcc-toolchain=/opt/rh/devtoolset-2/root/usr/"` and that appears to have fixed the builds. The flag is being passed to clang now (I assume) and not on to gcc when python builds.

If I understand right, setting that flag should not interfere with the `-DCMAKE_CXX_FLAGS_RELEASE=-I/usr/include/nvidia/"` setting as that should just be appended to the flag I set, correct?

I don't think this change should break anything, so if this looks good to you @peastman, I will remove all my debugging lines and we can move forward with the PR

**Comment by mpharrigan** [comment]
> One is that clang and gcc use different implementations of the C++ standard library by default.

on mac, they use their own libc++ but on linux it prefers to use gcc's libstdc++

**Comment by Lnaden** [comment]
Woo everything is working! I'm going to merge this now and we'll monitor it for a few days. If nothing appears to break, we will merge the one one on the [main conda-recipes](https://github.com/omnia-md/conda-recipes/pull/761) repo and make this live.

@peastman @jchodera just pining in notification since this will be a significant change to the builds going forward.

**Comment by peastman** [comment]
Will it still be possible to do builds with the old environment when needed?  We're preparing to do a 7.1.1 patch update to OpenMM, and it's important that gets done in the same environment we used for 7.1.0.  Same for any additional 7.1.x updates we might do in the future.

**Comment by jchodera** [comment]
Automatically: Not after we merge https://github.com/omnia-md/conda-recipes/pull/761, so we might want to get 7.1.1 released ASAP if we want to do that automatically.

Manually: In perpetuity. The [`omnia-build-box`](https://hub.docker.com/r/jchodera/omnia-build-box/) docker image isn't going anywhere.

**Comment by Lnaden** [comment]
As @jchodera said, I am only making this merge to the `conda-dev-recipes` for now, but I have not merged the main repo's PR of the same nature yet. I will hold off on that until the 7.1.1 bugfix is published.

The 7.1.1 patch may also be a good time to revisit the [Windows Python 3.6](https://github.com/pandegroup/openmm/issues/1758) build which appears on the surface to have the same symptom that the OSX builds here had (could it be a VCXX version vs python version?)

**Pull request merged**
