### PR TITLE
[WIP] [openmm-dev] Debugging

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Huh.  Pinning `fftw3f` to 3.3.3 works.  I wonder if the `fftw3f` 3.3.4 is just broken for the py3.4 `osx` package.  I can try rebuilding those.

In the meantime, @peastman, if `fftw3f` 3.3.3 will work for the release candidate, we're good to go!

**Comment by peastman** [comment]
Strange!  But I have no reason to think there's anything wrong with using 3.3.3, so that seems like a fine solution.

Thanks for debugging this!

**Comment by jchodera** [comment]
Sorry it took so long!  I had no idea what I was doing, so it was literally just trying a bunch of random things people suggested.

**Comment by peastman** [comment]
Shouldn't you remove the debugging code before merging?

By the way, here's the release notes from FFTW: http://www.fftw.org/release-notes.html.  Nothing in 3.3.4 sounds very important for us.

**Comment by jchodera** [comment]
Whoops, was too enthusiastic.  Will remove the core in the next PR.

**Pull request merged**
