### PR TITLE
add pyemma

### PR DESCRIPTION
**Pull request by marscher**
The method obtains the version from setup.py and is available in conda-build>=2

### CODE REVIEW

**Comment by marscher** [comment]
It seems conda-build-all tries to import "config" which is in another place in conda-build-2.0.1.

**Comment by marscher** [comment]
please do not merge yet, the versioning is still not working...

**Comment by jchodera** [comment]
I think we've also still broken building for everything here: See #41

**Comment by marscher** [comment]
I thought they deprecated/removed the post-build versioning via __conda_version__.txt for conda-build-2.0 but they didn't. Since it is the only working method for now, I'll stick to that.

Does the upload phase of our conda-build-all script just upload everything in the pkg dir or does it try to guess the names from the recipes? There are some errors that the files with version "0" can not be found, which is of course true, since the meta.yaml does declare it at this time step. 

If it uploads everything we are fine, otherwise we have a problem again.

**Comment by jchodera** [comment]
The [upload logic](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L245-L282), where it just gets the `filename` from [`get_bldpkg_path(m, python, numpy)`](https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L215-L228). I don't think this uploads everything.

**Comment by marscher** [comment]
So it will fail, since the version in the metadata got overwritten later on...

**Comment by jchodera** [comment]
Sorry to have neglected this, @marscher! Is this ready to merge?

**Pull request closed without merging**
