### PR TITLE
[WIP] Try to fix failing builds

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like `openmm` added `numpy` as a dependency!

Now it's failing to find python 3.6 packages for `sphinxcontrib-autodoc_doxygen`:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - sphinxcontrib-autodoc_doxygen
```

**Comment by jchodera** [comment]
This is the current problem: https://github.com/omnia-md/conda-recipes/pull/716

**Comment by jchodera** [comment]
@Lnaden : Can you retrigger the build here once https://github.com/omnia-md/conda-recipes/pull/716 is merged and the new `sphinxcontrib-*` packages are rebuilt?

**Comment by Lnaden** [comment]
Builds restarted, I'll check back on them in a bit

**Comment by jchodera** [comment]
Thanks!

Looks like we're running into more package issues:
```
...
BUILD START: openmm-7.2.0-py36_0
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/conda_build/build.py", line 1493, in build_tree
    config=config)
  File "/anaconda/lib/python3.6/site-packages/conda_build/build.py", line 1016, in build
    create_env(config.build_prefix, specs, config=config)
  File "/anaconda/lib/python3.6/site-packages/conda_build/build.py", line 683, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/anaconda/lib/python3.6/site-packages/conda/plan.py", line 473, in install_actions
    update_deps, pinned)
  File "/anaconda/lib/python3.6/site-packages/conda/plan.py", line 648, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/anaconda/lib/python3.6/site-packages/conda/resolve.py", line 802, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/anaconda/lib/python3.6/site-packages/conda/resolve.py", line 856, in solve
    self.find_conflicts(specs)
  File "/anaconda/lib/python3.6/site-packages/conda/resolve.py", line 371, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - sphinxcontrib-autodoc_doxygen -> python 3.4* -> openssl 1.0.1*
  - sphinxcontrib-autodoc_doxygen -> python 3.4* -> xz 5.0.5
```
Where do `xz` and `openssl` come from? Has python 3.4 support been dropped for them?

If so, we can probably drop python 3.4 from the dev builds, and we may have to for the regular conda-recipes as well if it is breaking things there.

**Comment by Lnaden** [comment]
The problem is actually still `sphinxcontrib-autodoc_doxygen`. The Python3.6 builds for it are not compiling, and I can't see any error or rules that would prevent them from building. There are a few other packages that just are not building the 3.6 versions with no error or indication they should be skipped

**Comment by jchodera** [comment]
@lnaden: I've just retriggered the builds to see if this is still broken.

Are we still stuck on `sphinxcontrib-autodoc_doxygen`?

If so, maybe we can disable the Python 3.6 builds in this repo for now? Maybe there's a way to tell `conda-build-all` to only build with 2.7, 3.4, and 3.5?

**Comment by Lnaden** [comment]
@jchodera 

> Are we still stuck on `sphinxcontrib-autodoc_doxygen`?

The short answer is "No:" omnia-md/conda-recipes#723

The long answer is several factors: 

It requires a hack job because Sphinx likes to change what is and is not shipped with their software. 1.3.1 what we used to build on is not built on 3.6 so we need to update to the next version which is 1.5.1. They stopped shipping a number of LaTeX packages with their software but sill use them. 

OpenMM does a hard coded `\renewcommand{DUspan}` which is a Sphinx function that was changed in 1.5+ to `DUrole` with no backport which causes a LaTeX compile error. 

The *correct* way to fix it will be to release an OpenMM fix which changes out the hard coded command AND then updates which version of Sphinx we build against, until then, I just made a patch since its really a matter of typesetting and not a change to OpenMM's functional code.

**Comment by Lnaden** [comment]
The patch on this is not working since the pr gets the raw code from master, so the patch is not valid. I made a PR on OpenMM directly to apply the changes the patch makes as a proper PR with an actual solution instead of the hack that is the patch.

**Comment by Lnaden** [comment]
The linux builds are now completing, the OSX ones hung due to some odd conda server overload, I restarted that one. The OSX Python 2.7 build made it through though before the conda backend problem

**Pull request merged**
