### PR TITLE
Use conda-build-all from omnia/conda-recipes

### PR DESCRIPTION
**Pull request by jchodera**
Uses `conda-build-all` from https://github.com/omnia-md/conda-recipes

cc: https://github.com/omnia-md/conda-dev-recipes/issues/4

### CODE REVIEW

**Comment by jchodera** [comment]
I'm not quite sure why `conda-build-all` didn't do anything here:
https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/102207153#L118

**Comment by jchodera** [comment]
@rmcgibbo: Any idea why `conda-build-all` isn't doing anything in travis?  I've already removed the `--check-against omnia` flag, so it should be building `openmm-dev`, even in the PR.

**Comment by rmcgibbo** [comment]
Not sure. I would try running the same command locally or maybe running with some of the --verbose flags.

**Comment by jchodera** [comment]
Huh:

```
mski1776:conda-dev-recipes.jchodera choderaj$ ./conda-build-all * --verbose
Considering recipes in the following order:
openmm-dev

Fetching package metadata: ............
```

**Comment by rmcgibbo** [comment]
try `-vvv`

**Comment by rmcgibbo** [comment]
```
    p.add_argument(
        '-v', '--verbose',
        help='Give more output. Option is additive, and can be used up to 3 times.',
        dest='verbose',
        action='count',
    )
```

**Comment by jchodera** [comment]
`required_builds()` is returning `[]` here:
https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L321

**Comment by jchodera** [comment]
```
mski1776:conda-dev-recipes.jchodera choderaj$ ./conda-build-all openmm-dev --verbose -vv
Considering recipes in the following order:
openmm-dev

Fetching package metadata: ............
Package exists on anaconda.org: openmm-dev
  full_name: openmm-dev-7.0.0.dev0-py27_0.tar.bz2
  channel:   https://conda.anaconda.org/omnia/osx-64/
  md5:       46207cdf3fedaecb1f89e2e1ba12cdc3
Package exists on anaconda.org: openmm-dev
  full_name: openmm-dev-7.0.0.dev0-py34_0.tar.bz2
  channel:   https://conda.anaconda.org/omnia/osx-64/
  md5:       8e82141e3c32d13a338df8e3677746af
Package exists on anaconda.org: openmm-dev
  full_name: openmm-dev-7.0.0.dev0-py35_0.tar.bz2
  channel:   https://conda.anaconda.org/omnia/osx-64/
  md5:       de985ba844b027efb09da365075a0841
```

Ahhhhh

**Comment by jchodera** [comment]
So it's checking against `omnia` even without the `--check-against` flag.

**Comment by rmcgibbo** [comment]
it's in `channel_urls`, I assume?

**Comment by jchodera** [comment]
Nope:

```
channel_urls = ()
```

It must be picking it up from the fact that the `.travis.yml` has

```
        conda config --add channels omnia;
```

Will try to eliminate this

**Comment by rmcgibbo** [comment]
no, that won't work, because then it won't be able to get fftw

**Comment by rmcgibbo** [comment]
ill look in the conda/conda source for a workaround.

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
It's not as simple as just letting the `args.force` argument force all packages in `metadatas` to be queued for building, is it?

**Comment by rmcgibbo** [comment]
Add the keyword argument `override_channels=True` to this function call: https://github.com/omnia-md/conda-recipes/blob/master/conda-build-all#L258

**Comment by jchodera** [comment]
Much better solution!

**Comment by jchodera** [comment]
cc: https://github.com/omnia-md/conda-recipes/pull/419

**Comment by rmcgibbo** [comment]
the syntax of multi-line bash inside a yaml file is a headache -- you might want to just copy out the bash content into a separate .sh file, and then just `source` it from the travis.yml

**Comment by jchodera** [comment]
You're right: https://github.com/travis-ci/travis-ci/issues/497

**Comment by jchodera** [comment]
I'm confused by the `swigInputBuilder.py` error:

```
30%] Creating OpenMM Python swig input files...
Traceback (most recent call last):
  File "/anaconda/conda-bld/work/build/python/src/swig_doxygen/swigInputBuilder.py", line 719, in <module>
    main()
  File "/anaconda/conda-bld/work/build/python/src/swig_doxygen/swigInputBuilder.py", line 687, in main
    skipAdditionalMethods, swigVersion) = parseCommandLine()
  File "/anaconda/conda-bld/work/build/python/src/swig_doxygen/swigInputBuilder.py", line 659, in parseCommandLine
    opts, args_proper = getopt.getopt(sys.argv[1:], 'hi:c:o:d:a:z:s:v:')
  File "/anaconda/envs/_build/lib/python2.7/getopt.py", line 90, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/anaconda/envs/_build/lib/python2.7/getopt.py", line 194, in do_shorts
    opt)
getopt.GetoptError: option -v requires argument
make[2]: *** [python/src/swig_doxygen/swig_lib/python/pythonprepend.i] Error 1
make[1]: *** [wrappers/python/CMakeFiles/BuildModule.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Built target ApiWrappers
make: *** [all] Error 2
Command failed: /bin/bash -x -e /io/openmm-dev/build.sh
```

Could this be a swig error?

**Comment by jchodera** [comment]
Also confused by the `osx` errors:

```
[ 34%] Creating OpenMM Python module sources with swig...
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'python.swg'
OpenMM.i:2: Error: Unable to find 'factory.i'
OpenMM.i:4: Error: Unable to find 'std_string.i'
OpenMM.i:5: Error: Unable to find 'std_iostream.i'
OpenMM.i:6: Error: Unable to find 'std_map.i'
OpenMM.i:7: Error: Unable to find 'std_pair.i'
OpenMM.i:8: Error: Unable to find 'std_set.i'
OpenMM.i:9: Error: Unable to find 'std_vector.i'
OpenMM.i:26: Error: Unable to find 'windows.i'
make[2]: *** [python/src/swig_doxygen/OpenMMSwig.cxx] Error 1
make[1]: *** [wrappers/python/CMakeFiles/BuildModule.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by rmcgibbo** [comment]
I see `Swig version must be 1.3.39 or greater for Python 2! (You have )` [here](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/102265241#L391) which looks like OpenMM's cmake failed to parse the version number of swig.

**Comment by rmcgibbo** [comment]
and also https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/102265241#L316-L319, so maybe there's something wrong with the in conda.

**Comment by rmcgibbo** [comment]
you should pin to the same version that we use inside pandegroup/openmm's travis, which is 3.0.7 I think.

**Comment by jchodera** [comment]
> you should pin to the same version that we use inside pandegroup/openmm's travis, which is 3.0.7 I think.

We don't pin this for the [openmm release recipe](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml#L24) yet.

**Comment by rmcgibbo** [comment]
Still.

**Comment by jchodera** [comment]
> you should pin to the same version that we use inside pandegroup/openmm's travis, which is 3.0.7 I think.

Also, this kind of crap is _exactly_ why it's a bad idea for this recipe to live outside of and not be tested by the `pandegroup/openmm` travis.

**Comment by rmcgibbo** [comment]
That wouldn't have even helped anyways.

**Comment by rmcgibbo** [comment]
looks like it's working now.

**Comment by jchodera** [comment]
@rmcgibbo, have you seen an error like this before with `git` on AppVeyor?

```
Command '['C:\\cygwin\\bin\\git.exe', 'clone', '--mirror', 'https://github.com/pandegroup/openmm.git', '/cygdrive/c/Miniconda/conda-bld/git_cache/__github.com_pandegroup_openmm.git']' returned non-zero exit status 3328
```

Full traceback:

```
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 190, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 266, in provide
    git_source(meta, recipe_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 115, in git_source
    cwd=recipe_dir, check_exit_code=True)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 231, in execute
    output=(stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\cygwin\\bin\\git.exe', 'clone', '--mirror', 'https://github.com/pandegroup/openmm.git', '/cygdrive/c/Miniconda/conda-bld/git_cache/__github.com_pandegroup_openmm.git']' returned non-zero exit status 3328

ERROR: File does not exist: C:\Miniconda\conda-bld\win-32\openmm-dev-7.0.0.dev0-py27_0.tar.bz2
[conda-build-all] Error: one or more packages failed to build (win-32)
  openmm-dev-7.0.0.dev0-py27_0.tar.bz2
Command exited with code 1
```

**Comment by rmcgibbo** [comment]
I think I have seen that before. In the past, I just fixed it by having the
recipe pull from github as a zip archive.

http://help.appveyor.com/discussions/problems/539-cloning-gyp-fails ?

@rmcgibbo https://github.com/rmcgibbo, have you seen an error like this
before with git on AppVeyor?

Command '['C:\cygwin\bin\git.exe', 'clone', '--mirror',
'https://github.com/pandegroup/openmm.git',
'/cygdrive/c/Miniconda/conda-bld/git_cache/__github.com_pandegroup_openmm.git']'
returned non-zero exit status 3328

Full traceback:

Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py",
line 190, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py",
line 468, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py",
line 391, in execute
    override_channels=args.override_channels,
include_recipe=args.include_recipe)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line
266, in provide
    git_source(meta, recipe_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line
115, in git_source
    cwd=recipe_dir, check_exit_code=True)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line
231, in execute
    output=(stdout, stderr))
subprocess.CalledProcessError: Command '['C:\cygwin\bin\git.exe',
'clone', '--mirror', 'https://github.com/pandegroup/openmm.git',
'/cygdrive/c/Miniconda/conda-bld/git_cache/__github.com_pandegroup_openmm.git']'
returned non-zero exit status 3328

ERROR: File does not exist:
C:\Miniconda\conda-bld\win-32\openmm-dev-7.0.0.dev0-py27_0.tar.bz2
[conda-build-all] Error: one or more packages failed to build (win-32)
  openmm-dev-7.0.0.dev0-py27_0.tar.bz2
Command exited with code 1

**Comment by jchodera** [comment]
Hm:

```
CustomManyParticleForceImpl.cpp
[ 31%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/CustomNonbondedForce.cpp.obj
CustomNonbondedForce.cpp
C:\Miniconda\conda-bld\work\openmm-master\openmmapi\src\CustomNonbondedForce.cpp(265) : error C2440: 'initializing' : cannot convert from 'std::_Tree<_Traits>::const_iterator' to 'std::_Tree<_Traits>::iterator'
        with
        [
            _Traits=std::_Tset_traits<int,std::less<int>,std::allocator<int>,false>
        ] 
        No constructor could take the source type, or constructor overload resolution was ambiguous 
C:\Miniconda\conda-bld\work\openmm-master\openmmapi\src\CustomNonbondedForce.cpp(267) : error C2440: 'initializing' : cannot convert from 'std::_Tree<_Traits>::const_iterator' to 'std::_Tree<_Traits>::iterator'
        with
        [
            _Traits=std::_Tset_traits<int,std::less<int>,std::allocator<int>,false>
        ] 
        No constructor could take the source type, or constructor overload resolution was ambiguous 
C:\Miniconda\conda-bld\work\openmm-master\openmmapi\src\CustomNonbondedForce.cpp(281) : error C2440: 'initializing' : cannot convert from 'std::_Tree<_Traits>::const_iterator' to 'std::_Tree<_Traits>::iterator'
        with
        [
            _Traits=std::_Tset_traits<int,std::less<int>,std::allocator<int>,false>
        ] 
        No constructor could take the source type, or constructor overload resolution was ambiguous 
C:\Miniconda\conda-bld\work\openmm-master\openmmapi\src\CustomNonbondedForce.cpp(283) : error C2440: 'initializing' : cannot convert from 'std::_Tree<_Traits>::const_iterator' to 'std::_Tree<_Traits>::iterator'
        with
        [
            _Traits=std::_Tset_traits<int,std::less<int>,std::allocator<int>,false>
        ] 
        No constructor could take the source type, or constructor overload resolution was ambiguous 
jom: C:\Miniconda\conda-bld\work\openmm-master\build\CMakeFiles\OpenMM.dir\build.make [CMakeFiles\OpenMM.dir\openmmapi\src\CustomNonbondedForce.cpp.obj] Error 2
jom: C:\Miniconda\conda-bld\work\openmm-master\build\CMakeFiles\Makefile2 [CMakeFiles\OpenMM.dir\all] Error 2
jom: C:\Miniconda\conda-bld\work\openmm-master\build\Makefile [all] Error 2

C:\Miniconda\conda-bld\work\openmm-master\build>if errorlevel 1 exit 1 
```

**Comment by jchodera** [comment]
I'll try to fix appveyor separately.

**Comment by rmcgibbo** [comment]
https://github.com/omnia-md/conda-dev-recipes/pull/5#issuecomment-171780559 is because you're trying to build with a compiler that's not supported (vs 2008). this is why openmm doesn't support py27 on windows. you could probably also skip the 32-bit builds on windows.

the py34 windows errors are when linking FFTW `LINK : fatal error LNK1104: cannot open file 'VCOMP.lib'`. I think this is related to OpenMP not being supported. It could be a bug with the fftw3 package.

I think there's also a py35 issue with those fftw3 packages because I tried to make static libraries, which seemed like a good idea in theory, but I don't think they work with VS 2015. So it might just be a better idea to use fftw dlls instead.

**Comment by jchodera** [comment]
Ah, OK.  Thanks for the clarification.

For now, I've just (once again) disabled the `win` builds on AppVeyor since we don't need them.

**Comment by rmcgibbo** [comment]
+1 to that

**Pull request merged**
