### PR TITLE
Add --force flag

### PR DESCRIPTION
**Pull request by rmcgibbo**
necessary to actually upload the files

### CODE REVIEW

**Comment by jchodera** [comment]
Shoot, I thought I had done that. Sorry.

**Comment by rmcgibbo** [comment]
I also removed the logic that suppressed the failing exit status when on a non-pull-requests, which was suppressing the error from the uploads not going through due to no `--force` from indicating failure.

since this repo is going to be triggered by cron, only showing failures when TRAVIS_PULL_REQUEST is set doesn't really make sense.

**Comment by jchodera** [comment]
> since this repo is going to be triggered by cron, only showing failures when TRAVIS_PULL_REQUEST is set doesn't really make sense.

Agreed.

**Comment by jchodera** [comment]
Looks like this now fails on `osx`.

**Comment by jchodera** [comment]
Huzzah!

**Pull request merged**
